import { expect, test } from '@playwright/test'
import { TENANT } from './fixtures'

/**
 * The rail: every section reachable, and the three links that leave the admin.
 *
 * The outward links are worth a test each because their failure mode is
 * indistinguishable from working. A `target` that was dropped takes the
 * operator out of the screen they were editing; an `href` that was never
 * updated opens a 404 in a tab they may not look at. Both look like a link.
 */

test.beforeEach(async ({ page }) => {
  await page.goto(`/app/${TENANT.slug}`)
})

test('every section opens', async ({ page }) => {
  for (const label of [
    'Incidents',
    'Maintenance',
    'Page layout',
    'Agents',
    'Logs',
    'Options',
    'Controls',
  ]) {
    await page.getByRole('link', { name: label, exact: true }).click()
    // The rail marks where you are. Without this the test would pass on a
    // click that navigated nowhere.
    await expect(page.getByRole('link', { name: label, exact: true })).toHaveAttribute(
      'aria-current',
      'page',
    )
  }
})

test('Platform is hidden from a tenant that does not supervise the instance', async ({ page }) => {
  // Drawn only for the system tenant. A visible entry that answers 403 teaches
  // people the admin is broken.
  await expect(page.getByRole('link', { name: 'Platform', exact: true })).toHaveCount(0)
})

test('the guide opens in its own tab', async ({ page }) => {
  const link = page.getByRole('link', { name: /^Documentation/ })
  await expect(link).toHaveAttribute('href', '/docs/admin-guide.html')
  await expect(link).toHaveAttribute('target', '_blank')
  // rel, because target="_blank" without it hands the opened page a handle on
  // this one.
  await expect(link).toHaveAttribute('rel', /noopener/)

  // Served, not merely linked: the file is generated by `pnpm docs:build` into
  // the web app's public directory, and the whole point of the link is that it
  // reaches a reader who has no checkout.
  const response = await page.request.get('/docs/admin-guide.html')
  expect(response.status()).toBe(200)
  expect(await response.text()).toContain('<html')
})

test('the public page opens in its own tab, at this tenant', async ({ page }) => {
  const link = page.getByRole('link', { name: /^Public page/ })
  await expect(link).toHaveAttribute('href', `/s/${TENANT.slug}`)
  await expect(link).toHaveAttribute('target', '_blank')
})

test('reporting an issue carries the version', async ({ page }) => {
  const link = page.getByRole('link', { name: /^Report an issue/ })
  const href = await link.getAttribute('href')

  expect(href).toContain('github.com')
  expect(href).toContain('/issues/new')

  // The version is the point of the link. Decoded rather than pattern-matched
  // on the encoded form, so the assertion reads like the thing it checks.
  const body = decodeURIComponent(new URL(href!).searchParams.get('body') ?? '')
  expect(body).toMatch(/TERN v\d/)
  expect(body).toContain('What happened')

  // Nothing about who or where. This opens a form on a public tracker.
  expect(body).not.toContain(TENANT.name)
  expect(body).not.toContain(TENANT.slug)
})
